import os

import slappy

SLACK_VERIFICATION_TOKEN = os.environ['SLACK_VERIFICATION_TOKEN']
SLACK_WORKPLACE_TOKEN = os.environ['SLACK_WORKPLACE_TOKEN']
PORT = os.environ['PORT']

bot = slappy.Bot(PORT, SLACK_WORKPLACE_TOKEN, SLACK_VERIFICATION_TOKEN)
