import os

import slappy

SLACK_VERIFICATION_TOKEN = os.environ['SLACK_VERIFICATION_TOKEN']
SLACK_WORKPLACE_TOKEN = os.environ['SLACK_WORKPLACE_TOKEN']

bot = slappy.Bot(SLACK_WORKPLACE_TOKEN, SLACK_VERIFICATION_TOKEN)
