import os

import slappy

SLACK_SIGNING_SECRET = os.environ['SLACK_SIGNING_SECRET']
SLACK_WORKPLACE_TOKEN = os.environ['SLACK_WORKPLACE_TOKEN']

bot = slappy.Bot(SLACK_WORKPLACE_TOKEN, SLACK_SIGNING_SECRET)
